# 1. 빌드 스테이지
FROM eclipse-temurin:21-jdk-alpine AS build
    # Java 21 개발도구(JDK)가 설치된 경량화 리눅스(Alpine)을 가져와서,
    # 이 단계를 build라는 별명으로 부르겠다는 뜻
WORKDIR /app

# 빌드 도구 복사
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .

# 의존성 다운로드 (캐시 활용)
RUN chmod +x ./gradlew
    # gradlew라는 파일에 실행권한(+x)를 주는 명령어
RUN ./gradlew dependencies --no-daemon

# 소스 복사 및 빌드
COPY src src
RUN ./gradlew build -x test --no-daemon
    # 데몬(백그라운드 모드)을 쓰지 않고 일회성으로 빌드하라는 옵션
    # 내 컴퓨터에서 개발할 때는 빌드 속도를 위해 Gradle을 메모리에 계속 띄워두는데
    # 도커 빌드는 한 번 쓰고 버리는 일회성 환경이라,
    # 메모리 낭비하지 않고 빌드가 끝나면 깔끔하게 종료되도록 옵션을 사용함

# 2. 실행 스테이지
FROM eclipse-temurin:21-jre-alpine
    # 실행을 위한 전용 환경인 JRE(Java Runtime Environment)를 가져옴
    # 실행기만 있어서 훨씬 가벼움
WORKDIR /app
# 빌드된 jar 파일만 가져오기
COPY --from=build /app/build/libs/*-SNAPSHOT.jar app.jar
    # build라고 이름 붙인 스테이지에서 생성된 .jar 파일을 지금 이 스테이지로 복사해 와서 이름을 app.jar로 바꾸라는 의미
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]