spring:
  datasource:
    url: ${SPRING_DATA_SOURCE_URL:jdbc:postgresql://localhost:5432/pureflow}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: true # flyway: DB 초기화 하고 싶을 땐 false, 초기화하기 싫을 땐 true로 수정할 것
    clean-on-validation-error: true # 유효성 검사 오류 시 자동으로 clean 실행 (개발 환경에서 유용)

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operations-sorter: alpha
  api-docs:
    path: /api-docs

logging:
  level:
#    org.flywaydb: DEBUG
    org.springframework.security: DEBUG